client_config_backend: file
client_config:
    client_id: 66826545926-17l17bttu3d206lcvk3mlrkl4qlvoen8.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive